### ISSUE TITLE
FullyAttentionalBlock中维度处理问题

### ISSUE THREAD

**Issue by Seperendity** [maggiesong7/FullyAttentional#1]
很有趣的工作！看了代码后，发现代码中关于相似度计算的部分，和论文中描述的实现不太一致，比如论文中经过`Fullyattention`后的维度是`C*C*(H+W)`，但是代码中维度都是在H、W方向分别计算的，最后也没有出现维度中含有`H+W`的向量。请问是因为论文中那样解释起来更方便才那样表述的吗？还有个问题是`gamma`参数在这是起什么作用呢？希望能得到您的解答。

**Comment by maggiesong7** [comment]
1. 在代码中，通过在H、W方向计算注意力后，我们可以得到C*C*H以及C*C*W的两个维度的attention map，此处可以看作实际attention map维度为C*C*(H+W)；
2. gamma参数是nl里比较常用的一个可学习参数，主要是用来平衡加强后的特征与原特征间的权重。

**Comment by Seperendity** [comment]
非常感谢您的解答，期待您后续的工作！第一点明白的您的意思了，其实就是因为更好这样更好表述才写成论文中的形式的吧。针对第二点请问一下您有做过消融实验吗，加上可学习的参数是否效果会更好呢？

**Comment by maggiesong7** [comment]
在本模型中，加上可学习参数效果会略好，但是增长不是很多

**Comment by Seperendity** [comment]
好的，谢谢您
