### ISSUE TITLE
For pretrained weight

### ISSUE THREAD

**Issue by VitaLemonTea1** [maggiesong7/FullyAttentional#3]
Hi,
Great work! Can you provide the pretrained weight for ResNet101-deep.

**Comment by maggiesong7** [comment]
Hi,
Here is the pretrained weight for ResNet101-deep:
https://drive.google.com/drive/folders/1T9NCZm46C642AOnJzZD4ZQLXEaXKKHHI?usp=drive_link


发件人: Jinzhou Lin ***@***.***>
发送时间: 2024年11月12日 15:14
收件人: maggiesong7/FullyAttentional ***@***.***>
抄送: Subscribed ***@***.***>
主题: [maggiesong7/FullyAttentional] For pretrained weight (Issue #3)


Hi,
Great work! Can you provide the pretrained weight for ResNet101-deep.

**Comment by VitaLemonTea1** [comment]
Thanks！

**Comment by VitaLemonTea1** [comment]
It seems like I need permission to download the weight. I have submitted the application. Please review  it.
Thanks！

**Comment by maggiesong7** [comment]
I have changed the permission, I think you can download it now.

**Comment by VitaLemonTea1** [comment]
Successfully downloaded.
Thanks for your reply.
